For my project I decided to take a closer look at Denver, CO. I chose this city because I lived in Boulder for a year and would frequently make trips into the city of Denver. I also thought it would be interesting to take a look at a city that isn't on the coast, as the birth of the city doesn't involve ports and seaways. What was done during this project was a georectification of an old map over a map of the current state of that same area. The old map is a visual representation of an initiative done during the great depression that allotted grades to different neighborhoods and areas determining the amount of risk associated with investing in real estate in that area. Blocks that earned the grade of "A" were racially and ethnically homogeneous and would allow for the most growth, while blocks with a "D" grade were considered hazardous and had a more diverse racial makeup (Hillier, ESRI, 2002). This map was georectified over a map of united states census blocks from 2010. Each block contains data about the racial makeup up of said block. I chose to look at the percentage of how white each block is. The darker red the block, the higher the percent of white people residing there. Below is a zoomed out picture of the two maps rectified upon one another. 

![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Map Overview") 

This initiative, from 1933-1936, done by the FDR administration, is a blatant case of systemic, political racism. These blocks with large amounts of minorities were automatically considred less succeptible to growth. Whether or not it was true that they were less succeptible to growth, this labeling of "hazardous" would deter real estate moguls from investing in that block. Thus, a cycle of systemic oppression began in these minority heavy areas. However, this isn't entirely consistent with how the maps line up now. As seen below, park hill is given a "B" grading but if you look at the census data from 2010, that area has a large minority population. This begs us to question what factors went into that grading, and also what happened between 1933 and 2010 that allowed a shift in said racial makeup. To delve deeper, I looked at the area in the Social Explorer program and more specifically, what the percentage of households have a minimum income of $50,000 because that is a relatively basic income to live on. This area is actually relatively wealthy with only about 30% of households making less than $50,000 a year. That compares to the block to the north of it that has about 60% of households making under $50,000 a year. 

![alt text](https://github.com/introdh/intro-dh-tuckershelley/blob/master/Park%20Hill.png "Park Hill")

One large problem facing this mapping method is the politics involved in grouping these blocks together. It is a similar situation to gerrymandering. It's necessary to know what went into the decisions to group certain blocks together. This is also applicable for the new social explorer program as well. The changing of groupings can cause a huge difference in the turnout of the information. Another mistake at interpreting these maps is reading too much into this information. Maps can be used for good and also for bad according to Jeremy Crampton (Crampton, Blackwell, 2007). This implies that these maps being tools for interpretation along with most other big data sets. These would be much more insightful with some more information on how the data was made and collected.
